const TODOS = [
  {
    id: "1",
    title: "Build Todo App",
    description: "Create a complete todo app using React",
    isCompleted: false,
    priority: "High",
    dueDate: "2025-07-21",
    createdAt: "2025-07-17T10:00:00.000Z",
    tags: ["react", "frontend", "project", "context-api"],
    subtasks: [
      { id: "1-1", title: "Set up project structure", isCompleted: true },
      { id: "1-2", title: "Create context and reducer", isCompleted: false },
    ],
  },
  {
    id: "2",
    title: "Study JavaScript",
    description: "Revise promises, async/await, and ES6 features",
    isCompleted: false,
    priority: "Medium",
    dueDate: "2025-07-22",
    createdAt: "2025-07-17T11:15:00.000Z",
    tags: ["javascript", "es6", "promises", "async-await", "learning"],
    subtasks: [
      { id: "2-1", title: "Review closures", isCompleted: true },
      { id: "2-2", title: "Practice arrow functions", isCompleted: false },
    ],
  },
  {
    id: "3",
    title: "Apply for Frontend Jobs",
    description: "Update resume and apply to 5 companies",
    isCompleted: false,
    priority: "High",
    dueDate: "2025-07-19",
    createdAt: "2025-07-17T12:00:00.000Z",
    tags: ["jobs", "frontend", "career", "resume"],
    subtasks: [],
  },
  {
    id: "10",
    title: "Backup Codebase",
    description: "Push all recent changes to GitHub",
    isCompleted: false,
    priority: "Low",
    dueDate: "2025-07-18",
    createdAt: "2025-07-17T15:30:00.000Z",
    tags: ["git", "github", "version-control", "backup"],
    subtasks: [
      { id: "10-1", title: "Commit changes", isCompleted: true },
      { id: "10-2", title: "Push to repo", isCompleted: false },
    ],
  },
];
export default TODOS;
